# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'KotlinConf' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod "youtube-ios-player-helper", "~> 0.1.4"
  pod 'Mapbox-iOS-SDK', '~> 5.2'
  pod 'Nuke', '~> 8.3.1'
  pod 'MarqueeLabel'

end
