project 'konan.xcodeproj'
platform :ios, '9.0'

target 'konan' do
  use_frameworks!

  # Pods for konfswift
  pod 'SDWebImage', '~> 4.1.0'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'OMGHTTPURLRQ', '~> 3.2.2'
  pod 'Groot/ObjC', '~> 3.0-beta.1'
  pod 'ILGHttpConstants', '~> 2.0.0'

  #target 'konfswiftTests' do
  #  inherit! :search_paths
  #  # Pods for testing
  #end

end