platform :ios, '9.0'

target 'konfswift' do
  use_frameworks!

  # Pods for konfswift
  pod 'SDWebImage', '~> 4.1.0'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'TagListView-ObjC', '~> 0.1.1'
  pod 'PopupDialog', '~> 0.8'

  target 'konfswiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
